import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { workRequestService } from '../services/workRequestService';
import { campusService, type Campus } from '../services/campusService';
import { Upload, AlertCircle, CheckCircle, Clock } from 'lucide-react';
import toast from 'react-hot-toast';

export function WorkRequestIntakePage() {
  const navigate = useNavigate();
  const { user } = useAuth();

  // Form state
  const [campuses, setCampuses] = useState<Campus[]>([]);
  const [formData, setFormData] = useState({
    campus_id: '',
    property: '',
    is_historic: false,
    category: 'Small Task' as const,
    description: '',
  });


  const [lastSaved, setLastSaved] = useState<Date | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Load campuses on mount
  useEffect(() => {
    const loadCampuses = async () => {
      try {
        const data = await campusService.getCampuses();
        setCampuses(data);
      } catch (error) {
        console.error('Failed to load campuses:', error);
        toast.error('Failed to load campuses');
      }
    };
    loadCampuses();
  }, []);

  // Auto-save draft
  const saveDraft = useCallback(async () => {
    if (!user?.id || !formData.campus_id || !formData.property || !formData.description) {
      return; // Don't save incomplete forms
    }

    try {
      // Note: In a real app, this would save to a drafts table
      // For now, we're just showing the auto-save behavior
      setLastSaved(new Date());
    } catch (error) {
      console.error('Failed to save draft:', error);
    }
  }, [formData, user?.id]);

  // Auto-save every 2 seconds if form has changed
  useEffect(() => {
    const timer = setTimeout(() => {
      saveDraft();
    }, 2000);

    return () => clearTimeout(timer);
  }, [formData, saveDraft]);

  // Validate form
  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.campus_id) newErrors.campus_id = 'Campus is required';
    if (!formData.property.trim()) newErrors.property = 'Property is required';
    if (!formData.description.trim()) newErrors.description = 'Description is required';
    if (!formData.category) newErrors.category = 'Category is required';

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      toast.error('Please fix the errors below');
      return;
    }

    try {
      setIsSubmitting(true);

      const newWorkRequest = await workRequestService.createWorkRequest({
        request_number: '', // Will be generated by database
        campus_id: formData.campus_id,
        property: formData.property,
        is_historic: formData.is_historic,
        category: formData.category,
        description: formData.description,
        status: 'Intake',
        created_by: user!.id,
        estimated_cost: undefined,
      } as any);

      toast.success(`Work request ${newWorkRequest.request_number} created!`);
      navigate(`/work-requests/${newWorkRequest.id}`);
    } catch (error) {
      console.error('Failed to create work request:', error);
      toast.error('Failed to create work request');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCancel = () => {
    if (formData.property || formData.description) {
      if (window.confirm('Discard unsaved changes?')) {
        navigate('/dashboard');
      }
    } else {
      navigate('/dashboard');
    }
  };

  return (
    <div className="p-8 max-w-3xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-4xl font-heading font-bold text-primary-900 mb-2">
          Create Work Request
        </h1>
        <p className="text-neutral-600">
          Start a new facilities or construction request for one of our campuses
        </p>
      </div>

      {/* Auto-save indicator */}
      {lastSaved && (
        <div className="mb-6 p-3 bg-green-50 border border-green-200 rounded flex items-center gap-2 text-sm text-green-700">
          <CheckCircle className="w-4 h-4" />
          Draft saved at {lastSaved.toLocaleTimeString()}
        </div>
      )}

      {/* Form */}
      <form onSubmit={handleSubmit} className="card p-8 space-y-6">
        {/* Campus Selection */}
        <div>
          <label htmlFor="campus_id" className="block text-sm font-medium text-neutral-900 mb-2">
            Campus <span className="text-red-600">*</span>
          </label>
          <select
            id="campus_id"
            value={formData.campus_id}
            onChange={(e) => {
              setFormData({ ...formData, campus_id: e.target.value });
              if (errors.campus_id) setErrors({ ...errors, campus_id: '' });
            }}
            className={`w-full px-4 py-2 border ${
              errors.campus_id ? 'border-red-300' : 'border-neutral-300'
            } bg-white text-neutral-900 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all`}
          >
            <option value="">Select a campus...</option>
            {campuses.map((campus) => (
              <option key={campus.id} value={campus.id}>
                {campus.name}
              </option>
            ))}
          </select>
          {errors.campus_id && (
            <p className="mt-1 text-sm text-red-600 flex items-center gap-1">
              <AlertCircle className="w-4 h-4" />
              {errors.campus_id}
            </p>
          )}
        </div>

        {/* Property */}
        <div>
          <label htmlFor="property" className="block text-sm font-medium text-neutral-900 mb-2">
            Property / Location <span className="text-red-600">*</span>
          </label>
          <input
            id="property"
            type="text"
            value={formData.property}
            onChange={(e) => {
              setFormData({ ...formData, property: e.target.value });
              if (errors.property) setErrors({ ...errors, property: '' });
            }}
            placeholder="e.g., Historic Building A, Main Gallery, Pergola Area"
            className={`w-full px-4 py-2 border ${
              errors.property ? 'border-red-300' : 'border-neutral-300'
            } bg-white text-neutral-900 placeholder-neutral-400 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all`}
          />
          {errors.property && (
            <p className="mt-1 text-sm text-red-600 flex items-center gap-1">
              <AlertCircle className="w-4 h-4" />
              {errors.property}
            </p>
          )}
        </div>

        {/* Historic Property Toggle */}
        <div className="flex items-center gap-3 p-4 bg-neutral-50 border border-neutral-200">
          <input
            id="is_historic"
            type="checkbox"
            checked={formData.is_historic}
            onChange={(e) => setFormData({ ...formData, is_historic: e.target.checked })}
            className="w-4 h-4 accent-primary-500"
          />
          <label htmlFor="is_historic" className="flex-1">
            <p className="font-medium text-neutral-900">This is a historic property</p>
            <p className="text-xs text-neutral-600">
              Requires additional documentation (photos, materials log, method notes)
            </p>
          </label>
        </div>

        {/* Category */}
        <div>
          <label className="block text-sm font-medium text-neutral-900 mb-3">
            Category <span className="text-red-600">*</span>
          </label>
          <div className="space-y-2">
            {(['Small Task', 'Event Support', 'Construction Project'] as const).map((cat) => (
              <label key={cat} className="flex items-center gap-3 p-3 border border-neutral-200 hover:bg-neutral-50 cursor-pointer">
                <input
                  type="radio"
                  name="category"
                  value={cat}
                  checked={formData.category === cat}
                  onChange={(e) =>
                    setFormData({ ...formData, category: e.target.value as any })
                  }
                  className="w-4 h-4 accent-primary-500"
                />
                <span className="font-medium text-neutral-900">{cat}</span>
              </label>
            ))}
          </div>
          {errors.category && (
            <p className="mt-2 text-sm text-red-600 flex items-center gap-1">
              <AlertCircle className="w-4 h-4" />
              {errors.category}
            </p>
          )}
        </div>

        {/* Description */}
        <div>
          <label htmlFor="description" className="block text-sm font-medium text-neutral-900 mb-2">
            Description <span className="text-red-600">*</span>
          </label>
          <textarea
            id="description"
            value={formData.description}
            onChange={(e) => {
              setFormData({ ...formData, description: e.target.value });
              if (errors.description) setErrors({ ...errors, description: '' });
            }}
            placeholder="Describe the work that needs to be done..."
            rows={6}
            className={`w-full px-4 py-2 border ${
              errors.description ? 'border-red-300' : 'border-neutral-300'
            } bg-white text-neutral-900 placeholder-neutral-400 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all`}
          />
          {errors.description && (
            <p className="mt-1 text-sm text-red-600 flex items-center gap-1">
              <AlertCircle className="w-4 h-4" />
              {errors.description}
            </p>
          )}
          <p className="text-xs text-neutral-500 mt-1">
            {formData.description.length} characters
          </p>
        </div>

        {/* Form Actions */}
        <div className="flex gap-3 pt-4 border-t border-neutral-200">
          <button
            type="submit"
            disabled={isSubmitting}
            className="flex-1 btn-primary py-3 font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            {isSubmitting ? (
              <>
                <Clock className="w-5 h-5 animate-spin" />
                Creating...
              </>
            ) : (
              <>
                <CheckCircle className="w-5 h-5" />
                Create Work Request
              </>
            )}
          </button>
          <button
            type="button"
            onClick={handleCancel}
            className="btn-secondary py-3 px-6 font-medium"
          >
            Cancel
          </button>
        </div>

        {/* Info Box */}
        <div className="p-4 bg-blue-50 border border-blue-200 text-sm text-blue-700 space-y-2">
          <p className="font-medium flex items-center gap-2">
            <Upload className="w-4 h-4" />
            Next Steps
          </p>
          <ul className="list-disc list-inside space-y-1">
            <li>Once created, you'll be able to add cost estimates</li>
            <li>Client approval required before scheduling work</li>
            <li>For historic properties, upload documentation and materials log</li>
            <li>Track progress with weekly updates</li>
          </ul>
        </div>
      </form>
    </div>
  );
}
